[build]
  command = "npm run build"
  publish = "dist"

# Явные заголовки для MIME-типов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*.ttf"
  [headers.values]
    Content-Type = "font/ttf"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

# SPA-редирект с исключениями
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Path = [
    "!/assets/*",
    "!/fonts/*",
    "!/*.js",
    "!/*.css",
    "!/*.ttf",
    "!/*.png",
    "!/*.jpg",
    "!/*.svg",
    "!/*.ico"
  ]}